# Configuration file for fusionPlanning.py

# System type (e.g., "pushing")
system: "pushing"

# Object name to be manipulated
objectName: "crackerBox"

# Start state as a list [x, y, theta] for SE2 space
startState: [0.0, -0.7, 0.0]

# Goal state as a list [x, y, theta] for SE2 space  
goalState: [0.725, -0.7, 0.0]

# Planning time in seconds
planningTime: 10.0

# Replanning time in seconds (for future use)
replanningTime: 3.0

# Planner name (e.g., "fusion", "sst", "rrt")
plannerName: "fusion"

# Whether to visualize the planning tree
visualize: false

# Optimization model parameters
learning_rate: 0.001
num_epochs: 200
